import datetime
from fpdf import FPDF
from models.schemas import HealthAnalysis

class HealthReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(0, 51, 102)  # Dark Blue
        self.cell(0, 10, "VitalCheck AI - Personal Health Report", ln=1, align="C")
        self.ln(5)
        # Decorative line
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        self.set_y(-25)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        
        # Medical Disclaimer
        disclaimer = (
            "Disclaimer: This report is generated by AI for informational purposes only. "
            "It is not medical advice. Consult a qualified doctor for any medical decisions."
        )
        self.multi_cell(0, 4, disclaimer, align="C")
        self.ln(2)
        
        # Page number
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_health_report_pdf(analysis: HealthAnalysis, patient_name: str) -> bytes:
    """
    Generate a formatted PDF document containing the health analysis.
    
    Args:
        analysis: HealthAnalysis schema model instance.
        patient_name: Patient's name.
        
    Returns:
        bytes: The generated PDF content.
    """
    pdf = HealthReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=30)
    
    # Metadata Block
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Patient Name:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(60, 6, patient_name, 0, 0)
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Report Date:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, datetime.date.today().strftime("%B %d, %Y"), 0, 1)
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Health Score:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(60, 6, f"{analysis.health_score} / 100", 0, 0)
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Overall Risk:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, analysis.risk_level, 0, 1)
    
    pdf.ln(10)
    
    # Executive Summary
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 8, "1. Executive Summary", ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5, analysis.summary)
    pdf.ln(8)
    
    # Abnormal Findings
    if analysis.abnormal_parameters:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(180, 0, 0)  # Red
        pdf.cell(0, 8, "2. Abnormal Findings Detected", ln=1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for param in analysis.abnormal_parameters:
            pdf.cell(8, 5, "-", 0, 0, "R")
            pdf.cell(0, 5, param, ln=1)
        pdf.ln(8)
    else:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(0, 102, 51)  # Green
        pdf.cell(0, 8, "2. Findings", ln=1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 5, "No abnormal parameters detected in this report.", ln=1)
        pdf.ln(8)
        
    # Risk Factors
    if analysis.risk_factors:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 8, "3. Potential Risk Factors", ln=1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for factor in analysis.risk_factors:
            pdf.cell(8, 5, "-", 0, 0, "R")
            pdf.cell(0, 5, factor, ln=1)
        pdf.ln(8)
        
    # Lifestyle Recommendations
    if analysis.recommendations:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 8, "4. Lifestyle Recommendations", ln=1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for i, rec in enumerate(analysis.recommendations, 1):
            pdf.cell(8, 5, f"{i}.", 0, 0, "R")
            pdf.cell(0, 5, rec, ln=1)
        pdf.ln(8)
        
    # Questions for Doctor
    if analysis.doctor_questions:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 8, "5. Suggested Questions for Your Doctor", ln=1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for i, q in enumerate(analysis.doctor_questions, 1):
            pdf.cell(8, 5, f"{i}.", 0, 0, "R")
            pdf.cell(0, 5, q, ln=1)
            
    # Return as bytes
    return bytes(pdf.output())


class HealthPlanPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(0, 80, 60)  # Teal
        self.cell(0, 10, "VitalCheck AI - Personalised Health Plan", ln=1, align="C")
        self.ln(3)
        self.set_draw_color(0, 80, 60)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(8)

    def footer(self):
        self.set_y(-25)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        disclaimer = (
            "Disclaimer: This health plan is AI-generated for informational purposes only. "
            "It is not medical advice. Consult a qualified doctor before making changes."
        )
        self.multi_cell(0, 4, disclaimer, align="C")
        self.ln(2)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def _section_heading(pdf, number, title, color=(0, 80, 60)):
    """Render a numbered section heading."""
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*color)
    pdf.cell(0, 8, f"{number}. {title}", ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)


def _bullet_list(pdf, items):
    """Render a bulleted list of strings."""
    for item in items:
        pdf.cell(8, 5, "-", 0, 0, "R")
        pdf.multi_cell(0, 5, f"  {item}")


def generate_health_plan_pdf(analysis, patient_name: str) -> bytes:
    """
    Generate a formatted PDF containing the personalised 4-week health plan.

    Args:
        analysis: HealthAnalysis instance (with health_plan populated).
        patient_name: Patient's name.

    Returns:
        bytes: The generated PDF content.
    """
    plan = analysis.health_plan
    pdf = HealthPlanPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=30)

    # Metadata
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Patient Name:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(60, 6, patient_name, 0, 0)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Plan Date:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, datetime.date.today().strftime("%B %d, %Y"), 0, 1)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Health Score:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(60, 6, f"{analysis.health_score} / 100", 0, 0)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Risk Level:", 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, analysis.risk_level, 0, 1)
    pdf.ln(8)

    # 1. Diet Guidelines
    _section_heading(pdf, 1, "Diet Guidelines")
    _bullet_list(pdf, plan.diet_guidelines)
    pdf.ln(6)

    # 2. Exercise Plan
    _section_heading(pdf, 2, "Exercise Plan")
    _bullet_list(pdf, plan.exercise_plan)
    pdf.ln(6)

    # 3. Daily Habits
    _section_heading(pdf, 3, "Daily Habits to Track")
    _bullet_list(pdf, plan.daily_habits)
    pdf.ln(6)

    # 4. 4-Week Plan
    _section_heading(pdf, 4, "4-Week Progressive Plan")
    for week in plan.weekly_plan:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 60, 90)
        pdf.cell(0, 7, f"Week {week.week}: {week.focus}", ln=1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for goal in week.goals:
            pdf.cell(12, 5, "[ ]", 0, 0, "R")
            pdf.multi_cell(0, 5, f"  {goal}")
        pdf.ln(3)
    pdf.ln(4)

    # 5. Follow-up Actions
    _section_heading(pdf, 5, "Medical Follow-up Actions", color=(180, 0, 0))
    _bullet_list(pdf, plan.followup_actions)

    return bytes(pdf.output())

